# PistonQueue V${version}
# Make the target server the default one you log in to
# READ ME: all colours are orange by default just add & and colour
# to change the colours to your liking
# Please don't forget to replace SERVERNAME

# MOTD support has been moved to a PistonMOTD (https://www.spigotmc.org/resources/80567/) placeholder addon.
# If both PistonQueue and PistonMOTD are installed on your proxy, the following placeholders will be available in the PistonMOTD config:
# %pistonqueue_regular%, %pistonqueue_priority%, %pistonqueue_veteran%

# Placeholder for %server_name%
SERVER_NAME: "&cexample.org"

# Username regex
ENABLE_USERNAME_REGEX: true
USERNAME_REGEX: "[a-zA-Z0-9_]*"
USERNAME_REGEX_MESSAGE: "&6[PQ] Invalid username please use: %regex%"

# Tab auto completion
REGISTER_TAB: true

# Server is full message
SERVER_IS_FULL_MESSAGE: "%server_name% &6is full"

# It is not recommended decreasing this number (milliseconds)
SERVER_ONLINE_CHECK_DELAY: 500

# Where to send the queue position message and what to send.
POSITION_MESSAGE_CHAT: true
POSITION_MESSAGE_HOT_BAR: false
QUEUE_POSITION: "&6Position in queue: &l%position%"
POSITION_MESSAGE_DELAY: 10000

# This is a message to hide the actual reason of why you are getting kicked from the server.
ENABLE_KICK_MESSAGE: false
KICK_MESSAGE: "&6You have lost connection to the server"

# Failure protection for the queue
PAUSE_QUEUE_IF_TARGET_DOWN: true
PAUSE_QUEUE_IF_TARGET_DOWN_MESSAGE: "&6The main server is down. We will be back soon!"

# When the servers are down should we prevent new players from joining the proxy?
KICK_WHEN_DOWN: false
SERVER_DOWN_KICK_MESSAGE: "%server_name% &6is down please try again later :("
# %TARGET_SERVER%, %QUEUE_SERVER% and %SOURCE_SERVER% are placeholders for the server names
KICK_WHEN_DOWN_SERVERS:
  - "%TARGET_SERVER%"
  - "%QUEUE_SERVER%"
  # - "%SOURCE_SERVER%"
  # - "other-server"

# If a player gets kicked from the target server (it goes down/crashes), he gets sent into queue and waits.
IF_TARGET_DOWN_SEND_TO_QUEUE: true
IF_TARGET_DOWN_SEND_TO_QUEUE_MESSAGE: "&cThe target server is offline now! You have been sent to queue while it goes back online."

# Only send players back to queue if the kick message has these words. (lowercase)
DOWN_WORD_LIST:
  - "restarting"
  - "closed"
  - "went down"

# If something went wrong while queue -> target happens should the player be sent back into queue?
RECOVERY: true
RECOVERY_MESSAGE: "&cOops something went wrong... Putting you back in queue."

# Set the queue servers name that is in the proxy config file.
# Note that the target server is always the one you log in to first.
# The target server is the one that has a queue to protect it.
# Make sure you set the default server in proxy config correctly.
QUEUE_SERVER: "queue"
TARGET_SERVER: "main"

# Set this to true if you're a lobby or cracked/offline mode server.
# This option is required for those setups to work. Make your proxy sends source -> target.
# PistonQueue will redirect the player with source -> queue automatically if target is full.
# The player will be sent to the original target server after the queue.
ENABLE_SOURCE_SERVER: false
SOURCE_SERVER: "lobby"

# Connecting to server message
JOINING_TARGET_SERVER: "&6Connecting to the server..."

# Whether you want to set the target server as your target or just want to have the proxy decide based on original target.
FORCE_TARGET_SERVER: false

# Total people allowed to be connected to the queue network
# Make sure you set the BungeeCord/Velocity slots higher than the amount
# of people you get regularly for example 9000 and 9000 on the queue server
QUEUE_SERVER_SLOTS: 9000

# Queue move delay in milliseconds default is 1000ms
# please note this only guaranteed to not have issues 1000ms and higher
QUEUE_MOVE_DELAY: 1000

# Max players allowed to be moved into the target server at once with one queue move.
MAX_PLAYERS_PER_MOVE: 10

# Should the queue be always active or only when the target server is full?
# When activated you will always be sent into the queue server and then the target server.
ALWAYS_QUEUE: true

# Send an XP sound to every player who gets to position 5 or below in the queue
SEND_XP_SOUND: true

# The way shadow-bans should work on your server. Valid types are: LOOP, TEN_PERCENT
# LOOP: When reaching the end of the queue you will get put in front of it again.
# PERCENT: Loop, but you have a custom chance of getting in.
# KICK: You will be kicked from the queue server on joining it.
SHADOW_BAN_TYPE: "LOOP"

# Custom percentage for the shadow-ban type. Only used when SHADOW_BAN_TYPE is set to PERCENT.
PERCENT: 10

# LOOP: When you're shadow-banned you will be put in queue, but before joining it "fails" and you start all over again.
SHADOW_BAN_MESSAGE: "&6You have lost connection to the server"

# Permissions
QUEUE_BYPASS_PERMISSION: "queue.bypass"
ADMIN_PERMISSION: "queue.admin"

# Adding or removing queue types requires a full restart!!!
# The order number is checked from first to last.
QUEUE_TYPES:
  REGULAR:
    ORDER: 3
    # Max players of this type allowed on the target server
    SLOTS: 50
    # Special permission for the default queue type
    PERMISSION: "default"
    # Queue server tab list configuration use %position% to show the current position of the player
    # and use %wait% to show the estimated wait time of the player (not very accurate yet)
    # this only shows when your in the queue waiting to join use a separate plugin for your target server
    HEADER:
      - ""
      - " %server_name% "
      - ""
      - " %server_name% &bis full "
      - " Position in queue: &l%position% "
      - " &6Estimated time: &l%wait% "
      - ""
    FOOTER:
      - ""
      - " &6You can now donate to receive priority queue status, please visit donate.example.com "
      - ""
      - " &7contact: contact@example.com "
      - " discussion: https://discord.example.com "
      - " website: https://www.example.com "
      - " These are the only official %server_name% websites and contacts "
      - ""
  PRIORITY:
    ORDER: 2
    SLOTS: 30
    PERMISSION: "queue.priority"
    # Configs for priority queue tab list
    HEADER:
      - ""
      - " %server_name%"
      - ""
      - " %server_name% &bis full "
      - " Position in queue: &l%position% "
      - " &6Estimated time: &l%wait% "
      - ""
    FOOTER:
      - ""
      - " &6You have priority queue status please wait for an available slot on the server "
      - ""
      - " &7contact: contact@example.com "
      - " discussion: https://discord.example.com "
      - " website: https://www.example.com "
      - " These are the only official %server_name% websites and contacts "
      - ""
  VETERAN:
    ORDER: 1
    SLOTS: 20
    PERMISSION: "queue.veteran"
    # Configs for veteran queue tab list
    HEADER:
      - ""
      - " %server_name% "
      - ""
      - " %server_name% &bis full "
      - " Position in queue: &l%position% "
      - " &6Estimated time: &l%wait% "
      - ""
    FOOTER:
      - ""
      - " &6You have veteran queue status please wait for an available slot on the server "
      - ""
      - " &7contact: contact@example.com "
      - " discussion: https://discord.example.com "
      - " website: https://www.example.com "
      - " These are the only official %server_name% websites and contacts "
      - ""
