package Xera.Bungee.Queue.Bungee;

import java.util.List;

/**
 * Config
 */
public class Config {
    public static String SERVERISFULLMESSAGE, QUEUEPOSITION, JOININGMAINSERVER, QUEUEBYPASSPERMISSION, QUEUESERVER, QUEUEPRIORITYPERMISSION, REGEX, KICKMESSAGE, ADMINPERMISSION, MAINSERVER, AUTHSERVER, SERVERDOWNKICKMESSAGE, CUSTOMPROTOCOL;

    public static boolean POSITIONMESSAGEHOTBAR, ENABLEKICKMESSAGE, SERVERPINGINFOENABLE,
            ENABLEAUTHSERVER, ALWAYSQUEUE, CUSTOMPROTOCOLENABLE, REGISTERTAB, AUTHFIRST;

    public static int MAINSERVERSLOTS, QUEUEMOVEDELAY, QUEUESERVERSLOTS, SERVERONLINECHECKDELAY;

    public static List<String> SERVERPINGINFO, HEADER, FOOTER, HEADERPRIORITY, FOOTERPRIORITY;
}
