package Xera.Bungee.Queue.Bungee;

import java.util.List;

/**
 * Config
 */
public final class Config {
    protected static String SERVERISFULLMESSAGE, QUEUEPOSITION, JOININGMAINSERVER,
            QUEUEBYPASSPERMISSION, QUEUESERVER, QUEUEPRIORITYPERMISSION, REGEX,
            KICKMESSAGE, ADMINPERMISSION, MAINSERVER, AUTHSERVER, SERVERDOWNKICKMESSAGE,
            CUSTOMPROTOCOL, QUEUEVETERANPERMISSION, REGEXMESSAGE, PAUSEQUEUEIFMAINDOWNMESSAGE,
            SHADOWBANPERMISSION, SHADOWBANMESSAGE;

    protected static boolean POSITIONMESSAGEHOTBAR, ENABLEKICKMESSAGE, SERVERPINGINFOENABLE,
            ENABLEAUTHSERVER, ALWAYSQUEUE, CUSTOMPROTOCOLENABLE, REGISTERTAB, AUTHFIRST, POSITIONMESSAGECHAT,
            PAUSEQUEUEIFMAINDOWN, KICKWHENDOWN;

    protected static int MAINSERVERSLOTS, QUEUEMOVEDELAY, QUEUESERVERSLOTS, SERVERONLINECHECKDELAY;

    protected static List<String> SERVERPINGINFO, HEADER, FOOTER, HEADERPRIORITY, FOOTERPRIORITY, HEADERVETERAN, FOOTERVETERAN;
}
