package Xera.Bungee.Queue.Bungee;

import java.util.List;

/**
 * Lang
 */
public class Lang {
    public static String SERVERISFULLMESSAGE, QUEUEPOSITION, JOININGMAINSERVER, QUEUEBYPASSPERMISSION,
            HEADER, FOOTER, POSITIONMESSAGEHOTBAR, QUEUESERVER, QUEUEPRIORITYPERMISSION, HEADERPRIORITY,
            FOOTERPRIORITY, REGEX, KICKMESSAGE, ADMINPERMISSION, ENABLEKICKMESSAGE, MAINSERVER, AUTHSERVER,
            ENABLEAUTHSERVER, SERVERDOWNKICKMESSAGE, SERVERPINGINFOENABLE, ALWAYSQUEUE, CUSTOMPROTOCOL;

    public static int MAINSERVERSLOTS,QUEUEMOVEDELAY, QUEUESERVERSLOTS;

    public static List<String> SERVERPINGINFO;
}
