package Xera.Bungee.Queue.Bungee;

import java.util.List;

/**
 * Lang
 */
public class Lang {
    public static String SERVERISFULLMESSAGE, QUEUEPOSITION, JOININGMAINSERVER, QUEUEBYPASSPERMISSION,
            HEADER, FOOTER, QUEUESERVER, QUEUEPRIORITYPERMISSION, HEADERPRIORITY,
            FOOTERPRIORITY, REGEX, KICKMESSAGE, ADMINPERMISSION, MAINSERVER, AUTHSERVER, SERVERDOWNKICKMESSAGE, CUSTOMPROTOCOL;

    public static boolean POSITIONMESSAGEHOTBAR, ENABLEKICKMESSAGE, SERVERPINGINFOENABLE,
            ENABLEAUTHSERVER, ALWAYSQUEUE, CUSTOMPROTOCOLENABLE;

    public static int MAINSERVERSLOTS,QUEUEMOVEDELAY, QUEUESERVERSLOTS;

    public static List<String> SERVERPINGINFO;
}
