# XeraBungeeQueueBukkit V4.0.2
# Make the main server the default one you login to
# and then it should work if it doesnt add me on discord for help
# my discord is Leee#2021 add to ask any questions
# READ ME: all colours are orange by default just add & and colour
# to change the colours to your liking

# Username regex
REGEX: "[a-zA-Z0-9_]*"

# Server is full message
SERVERISFULLMESSAGE: "&66b6t is full"


# Position in queue message by default only sends in chat every 10 seconds
# you can have it on the hotbar by setting POSITIONMESSAGEHOTBAR: "false" to true
POSITIONMESSAGEHOTBAR: false
QUEUEPOSITION: "&6Position in queue: &l<position>"
ENABLEKICKMESSAGE: true
KICKMESSAGE: "&6You have lost connection to the server"
SERVERDOWNKICKMESSAGE: "&b6b&36t &6is down please try again later :("

# this shows the queue size when you hover over the ping on the server list
SERVERPINGINFOENABLE: true
SERVERPINGINFO:
  - "&b6b&36t &6Queue Size"
  - "&6Priority: &l%priority%"
  - "&6Regular: &l%regular%"
CUSTOMPROTOCOL: "&b6b&36t &61.8.x to 1.16.x"

# Set the queue servers name that is in the bungee config.yml
# Note that the main server is always the one you login to first
# The main server server is the one that has a queue to protect it
# make sure you set the default server in bungee config.yml correctly
QUEUESERVER: "queue"
MAINSERVER: "6b6t"
# set this to false if your a premium server
ENABLEAUTHSERVER: true
AUTHSERVER: "auth"


# Connecting to server message use <server> if you want it
# to just use the name of the default server
JOININGMAINSERVER: "&6Connecting to 6b6t"


# Max players allowed onto main server
MAINSERVERSLOTS: 100

# Total people allowed to be connected to the queue network
# Make sure you set the bungeecord slots higher then the amount
# of people you get regularly i set mine to 9000 and 9000 on the queue server
QUEUESERVERSLOTS: 9000


# Queue move delay in miliseconds default is 2000ms
# please note this only guaranteed to not have issues 2000ms and higher
QUEUEMOVEDELAY: 2000


# Always add players to queue to prevent server crashing from to many joins
ALWAYSQUEUE: true


# Permissions
QUEUEBYPASSPERMISSION: "queue.override"
QUEUEPRIORITYPERMISSION: "queue.priority"
ADMINPERMISSION: "queue.admin"


# Queue server tablist configuration use <position> to show the current position of the player
# and use <wait> to show the estimated wait time of the player(not very accurate yet)
# this only shows when your in the queue waiting to join use a separate plugin for your main server
HEADER: "\n&b6builders&36tools\n\n&66b6t is full\nPosition in queue: &l<position>\n&6Estimated time: &l<wait>\n"

FOOTER: "\n   &6You can now donate to receive priority queue status, please visit donate.6b6t.org   \n\n&7contact: nate@xera.ca\n
discussion: http://discord.6b6t.org\nwebsite: https://www.6b6t.org\nThese are the only official 6b6t websites and contacts\n"


# configs for priority queue tablist
HEADERPRIORITY: "\n&b6builders&36tools\n\n&66b6t is full\nPosition in queue: &l<position>\n&6Estimated time: &l<wait>\n"

FOOTERPRIORITY: "\n   &6You have priority queue status please wait for an available slot on the server   \n\n&7contact: nate@xera.ca\n
discussion: http://discord.6b6t.org\nwebsite: https://www.6b6t.org\nThese are the only official 6b6t websites and contacts\n"
