# PistonQueue V${project.version}
# Note - Operators and users with the permission "queue.admin" will be excluded from restrictions. ##

forceLocation: true # Force the user to remain in a certain location.

forcedWorldName: "world_the_end" # the name of the world to force the user to remain in
forcedX: 500 # the coordinates that the user must remain at.
forcedY: 256
forcedZ: 500

hidePlayers: true # Hide players from each other so that it looks like every user is alone in the world. This will also disable join/leave messages.
restrictMovement: true # Prevent players from moving.
forceGamemode: true # Force players to remain in a single gamemode
forcedGamemode: "spectator" # The gamemode to force players to remain in.
disableChat: true # Don't allow players to chat
disableCmd: true # Don't allow commands

protocol: true # Prevents sending unnecessary data to players and also makes own head visible in spectator. (like on 2b2t)

team: false # Show a players own name to himself in spectator menu.

# ProtocolLib only
disableDebug: true # Doesn't show the clients position on f3.