# PistonQueue V${project.version}
# Note - Operators and users with the permission "queue.admin" will be excluded from restrictions.

forceLocation: true # Force the user to remain in a certain position.
forcedWorldName: "world_the_end" # Forced world
forcedX: 500 # Forced x coordinate
forcedY: 256 # Forced y coordinate
forcedZ: 500 # Forced z coordinate

hidePlayers: true # Hide players from each other, so that it looks like every user is alone in the world. This will also disable join/leave messages.
restrictMovement: true # Prevent players from moving.
forceGamemode: true # Force players to remain in a gamemode.
forcedGamemode: "spectator" # The gamemode to force players to remain in.
disableChat: true # Don't allow players to chat.
disableCmd: true # Don't allow commands.

team: false # Show a players own name to himself in spectator menu.
teamName: "%playername%" # The name the user sees.

# ProtocolLib only
disableDebug: true # Doesn't show the clients position on F3.
noChunk: true # Do not send chunk data packets.
noTime: true # Do not send time packets.
noHealth: true # Do not send health packets.
noAdvancements: true # Do not send advancement packets.
noExperience: true # Do not send experience packets.
showHead: true # Does not send entity metadata anymore, causing that the entire player head is shown while in spectator.