name: XeraBungeeQueueBukkit
version: 1.3.0
api-version: 1.16
main: Xera.Bungee.Queue.Bukkit.XeraBungeeQueueBukkit
author: XeraPlugins
authors: [Nate Legault, Pistonmaster]
description: Bukkit companion for XeraBungeeQueue
website: http://www.xera.ca/
permissions:
  queue.admin:
    description: Lets you bypass the plugin.
    default: op
