name: LeeesBungeeQueue
version: 4.0.0
api-version: 1.16
main: Leees.Bungee.Queue.Bukkit.Main
authors: [Nate, Legault]
description: Bukkit companion plugin for LeeesBungeeQueue
website: https://www.6b6t.org