name: XeraBungeeQueueBukkit
version: ${project.version}
api-version: 1.16
main: ca.xera.bungee.queue.bukkit.XeraBungeeQueueBukkit
author: XeraPlugins
authors: [Nate Legault, Pistonmaster]
description: Bukkit companion for XeraBungeeQueue
website: http://www.xera.ca/
permissions:
  queue.admin:
    description: Lets you bypass the plugin.
    default: op
