name: XeraBungeeQueueBukkit
version: 1.0.0
api-version: 1.16
main: Xera.Bungee.Queue.Bukkit.XeraBungeeQueueBukkit
author: XeraPlugins
authors: [Nate, Legault]
description: Bukkit companion for XeraBungeeQueueBukkit
website: http://www.xera.ca/