# PistonQueue V${project.version}
# Make the main server the default one you log in to
# READ ME: all colours are orange by default just add & and colour
# to change the colours to your liking
# Please don't forget to replace SERVERNAME

# MOTD support has been moved to a PistonMOTD (https://www.spigotmc.org/resources/80567/) placeholder addon.
# If both PistonQueue and PistonMOTD are installed on your proxy, the following placeholders will be available in the PistonMOTD config:
# %pistonqueue_regular%, %pistonqueue_priority%, %pistonqueue_veteran%

SERVERNAME: "SERVERNAME"

# Username regex
ENABLE_USERNAME_REGEX: true
USERNAME_REGEX: "[a-zA-Z0-9_]*"
USERNAME_REGEX_MESSAGE: "&6[PQ] Invalid username please use: %regex%"

# Tab auto completion
REGISTER_TAB: true

# Server is full message
SERVER_IS_FULL_MESSAGE: "%server% &6is full"

# It is not recommended decreasing this number (milliseconds)
SERVER_ONLINE_CHECK_DELAY: 500

# Where to send the queue position message and what to send.
POSITION_MESSAGE_CHAT: true
POSITION_MESSAGE_HOTBAR: false
QUEUE_POSITION: "&6Position in queue: &l%position%"
POSITION_MESSAGE_DELAY: 10000

# This is a message to hide the actual reason of why you are getting kicked from the server.
ENABLE_KICK_MESSAGE: false
KICK_MESSAGE: "&6You have lost connection to the server"

# Failure protection for the queue
PAUSE_QUEUE_IF_MAIN_DOWN: true
PAUSE_QUEUE_IF_MAIN_DOWN_MESSAGE: "&6The main server is down. We will be back soon!"

# Time to wait for the server to come back up after it binding to the port again. (Seconds)
START_TIME: 30

# When the main server is down should you kick the player from the queue?
KICK_WHEN_DOWN: false
SERVER_DOWN_KICK_MESSAGE: "%server% &6is down please try again later :("

# If a player gets kicked from the main server (it goes down/crashes), he gets sent into queue and waits.
IF_MAIN_DOWN_SEND_TO_QUEUE: true
IF_MAIN_DOWN_SEND_TO_QUEUE_MESSAGE: "&cThe main server is offline now! You have been sent to queue while it goes back online."

# Only send players back to queue if the kick message has these words. (lowercase)
DOWN_WORD_LIST:
  - "restarting"
  - "closed"
  - "went down"

# If something went wrong while queue -> main happens should the player be sent back into queue?
RECOVERY: true
RECOVERY_MESSAGE: "&cOops something went wrong... Putting you back in queue."

# Set the queue servers name that is in the bungee config.yml
# Note that the main server is always the one you log in to first
# The main server is the one that has a queue to protect it
# Make sure you set the default server in bungee config.yml correctly
QUEUE_SERVER: "queue"
MAIN_SERVER: "main"

# Set this to true if you're a cracked/offline mode server.
# It is recommended to have the AuthServer first option enabled otherwise people will go into the queue first
# then Auth and main.
ENABLE_AUTH_SERVER: false
AUTH_SERVER: "auth"

# Have the auth server go first instead of the default settings which are Queue -> Auth -> and main
# This option will let you have the auth server go first then queue and the main server.
# You need to additionally set up your auth server to send you to the queue server after login
# DISCLAIMER: This feature is experimental and may cause some issues!
# It might also cause more issues because then the players aren't queued to join the auth server. It might overload.
# We will not provide support for this feature!!!
AUTH_FIRST: false

# Do you want people to join directly to the queue server to be able to get queued?
# Makes sense when having auth first and the plugin redirecting you instantly to the queue.
ALLOW_AUTH_SKIP: true

# Connecting to server message
JOINING_MAIN_SERVER: "&6Connecting to the server..."

# Max players per queue type allowed on the main server
REGULAR_SLOTS: 50
PRIORITY_SLOTS: 30
VETERAN_SLOTS: 20

# Whether you want to set the main server as your target or just want to have BungeeCord to decide.
FORCE_MAIN_SERVER: false

# Total people allowed to be connected to the queue network
# Make sure you set the BungeeCord/Velocity slots higher than the amount
# of people you get regularly for example 9000 and 9000 on the queue server
QUEUE_SERVER_SLOTS: 9000

# Queue move delay in milliseconds default is 1000ms
# please note this only guaranteed to not have issues 1000ms and higher
QUEUE_MOVE_DELAY: 1000

# Max players allowed to be moved into the main server at once.
MAX_PLAYERS_PER_MOVE: 10

# Should the queue be always active or only when the main server is full?
# When activated you will always be sent into the queue server and then the main server.
ALWAYS_QUEUE: true

# Send an XP sound to every player who gets to position 5 or below in the queue
SEND_XP_SOUND: true

# The way shadow-bans should work on your server. Valid types are: LOOP, TEN_PERCENT
# LOOP: When reaching the end of the queue you will get put in front of it again.
# TEN_PERCENT: Loop, but you have a ten percent chance of getting in.
# CUSTOM_PERCENT: Loop, but you have a custom chance of getting in.
# KICK: You will be kicked from the queue server on joining it.
SHADOW_BAN_TYPE: "LOOP"

# Custom percentage for the shadow-ban type. Only used when SHADOWBANTYPE is set to CUSTOM_PERCENT.
CUSTOM_PERCENT_PERCENTAGE: 20

# LOOP: When you're shadow-banned you will be put in queue, but before joining it "fails" and you start all over again.
SHADOW_BAN_MESSAGE: "&6You have lost connection to the server"

# Permissions
QUEUE_BYPASS_PERMISSION: "queue.bypass"
ADMIN_PERMISSION: "queue.admin"

QUEUES:
  NORMAL:
    PERMISSION: "default"
    # Queue server tab list configuration use %position% to show the current position of the player
    # and use %wait% to show the estimated wait time of the player (not very accurate yet)
    # this only shows when your in the queue waiting to join use a separate plugin for your main server
    HEADER:
      - ""
      - " %server% "
      - ""
      - " %server% &bis full "
      - " Position in queue: &l%position% "
      - " &6Estimated time: &l%wait% "
      - ""
    FOOTER:
      - ""
      - " &6You can now donate to receive priority queue status, please visit donate.SERVERNAME.org "
      - ""
      - " &7contact: someone@example.com "
      - " discussion: https://discord.example.com "
      - " website: https://www.example.com "
      - " These are the only official SERVERNAME websites and contacts "
      - ""
  PRIORITY:
    PERMISSION: "queue.priority"
    # Configs for priority queue tab list
    HEADER:
      - ""
      - " %server%"
      - ""
      - " %server% &bis full "
      - " Position in queue: &l%position% "
      - " &6Estimated time: &l%wait% "
      - ""
    FOOTER:
      - ""
      - " &6You have priority queue status please wait for an available slot on the server "
      - ""
      - " &7contact: someone@example.com "
      - " discussion: https://discord.example.com "
      - " website: https://www.example.com "
      - " These are the only official SERVERNAME websites and contacts "
      - ""
  VETERAN:
    PERMISSION: "queue.veteran"
    # Configs for veteran queue tab list
    HEADER:
      - ""
      - " %server% "
      - ""
      - " %server% &bis full "
      - " Position in queue: &l%position% "
      - " &6Estimated time: &l%wait% "
      - ""
    FOOTER:
      - ""
      - " &6You have veteran queue status please wait for an available slot on the server "
      - ""
      - " &7contact: someone@example.com "
      - " discussion: https://discord.example.com "
      - " website: https://www.example.com "
      - " These are the only official SERVERNAME websites and contacts "
      - ""
