# PistonQueue V${project.version}
# Make the main server the default one you login to
# READ ME: all colours are orange by default just add & and colour
# to change the colours to your liking
# Please don't forget to replace SERVERNAME

# MOTD support has been moved to a PistonMOTD (https://www.spigotmc.org/resources/80567/) placeholder addon.
# If both PistonQueue and PistonMOTD are installed on your proxy, the following placeholders will be available in the PistonMOTD config:
# %pistonqueue_regular%, %pistonqueue_priority%, %pistonqueue_veteran%

SERVERNAME: "SERVERNAME"

# Username regex
REGEX: "[a-zA-Z0-9_]*"
REGEXMESSAGE: "&6[PQ] Invalid username please use: %regex%"

# Tab auto completion
REGISTERTAB: true

# Server is full message
SERVERISFULLMESSAGE: "%server% &6is full"

# It is not recommended to decrease this number (milliseconds)
SERVERONLINECHECKDELAY: 500

# Where to send the queue position message and what to send.
POSITIONMESSAGECHAT: true
POSITIONMESSAGEHOTBAR: false
QUEUEPOSITION: "&6Position in queue: &l%position%"
POSITIONMESSAGEDELAY: 10000

# This is a message to hide the actual reason of why you are getting kicked from the server.
ENABLEKICKMESSAGE: false
KICKMESSAGE: "&6You have lost connection to the server"

# Failure protection for the queue
PAUSEQUEUEIFMAINDOWN: true
PAUSEQUEUEIFMAINDOWNMESSAGE: "&6The main server is down. We will be back soon!"

# Time to wait for the server to come back up after it binding to the port again. (Seconds)
STARTTIME: 30

# When the main server is down should you kick the player from the queue?
KICKWHENDOWN: false
SERVERDOWNKICKMESSAGE: "%server% &6is down please try again later :("

# If a player gets kicked from the main server (it goes down/crashes), he gets sent into queue and waits.
IFMAINDOWNSENDTOQUEUE: true
IFMAINDOWNSENDTOQUEUEMESSAGE: "&cThe main server is offline now! You have been sent to queue while it goes back online."

# Only send players back to queue if the kick message has these words. (lowercase)
DOWNWORDLIST:
  - "restarting"
  - "closed"
  - "went down"

# If something went wrong while queue -> main happens should the player be sent back into queue?
RECOVERY: true
RECOVERYMESSAGE: "&cOops something went wrong... Putting you back in queue."

# Set the queue servers name that is in the bungee config.yml
# Note that the main server is always the one you login to first
# The main server server is the one that has a queue to protect it
# Make sure you set the default server in bungee config.yml correctly
QUEUESERVER: "queue"
MAINSERVER: "main"

# Set this to true if you're a cracked/offline mode server.
# It is recommended to have the AuthServer first option enabled otherwise people will go into the queue first
# then Auth and main.
ENABLEAUTHSERVER: false
AUTHSERVER: "auth"

# Have the auth server go first instead of the default settings which are Queue -> Auth -> and main
# This option will let you have the auth server go first then queue and the main server.
# You need to additionally setup your auth server to send you to the queue server after login
# DISCLAIMER: This feature is experimental and may cause some issues!
# It might also cause more issues because then the players aren't queued to join the auth server. It might overload.
# We will not provide support for this feature!!!
AUTHFIRST: false

# Do you want people to join directly to the queue server to be able to get queued?
# Makes sense when having auth first and the plugin redirecting you instantly to the queue.
ALLOWAUTHSKIP: true

# Connecting to server message
JOININGMAINSERVER: "&6Connecting to the server..."

# Max players per queue type allowed on the main server
REGULARSLOTS: 50
PRIORITYSLOTS: 30
VETERANSLOTS: 20

# Whether you want to set the main server as your target or just want have bungeecord to decide.
FORCEMAINSERVER: true

# Total people allowed to be connected to the queue network
# Make sure you set the bungeecord/velocity slots higher then the amount
# of people you get regularly for example 9000 and 9000 on the queue server
QUEUESERVERSLOTS: 9000

# Queue move delay in milliseconds default is 1000ms
# please note this only guaranteed to not have issues 1000ms and higher
QUEUEMOVEDELAY: 1000

# Should the queue be always active or only when the main server is full?
# When activated you will always be sent into the queue server and then the main server.
ALWAYSQUEUE: true

# The way shadow bans should work on your server. Valid types are: LOOP, TENPERCENT
# LOOP: When reaching the end of the queue you will get put in front of it again.
# TENPERCENT: You have a ten percent chance of getting in.
SHADOWBANTYPE: "LOOP"

# LOOP: When your shadow banned you will be put in queue, but before joining it "fails" and you start all over again.
SHADOWBANMESSAGE: "&6You have lost connection to the server"

# Permissions
QUEUEBYPASSPERMISSION: "queue.bypass"
QUEUEPRIORITYPERMISSION: "queue.priority"
QUEUEVETERANPERMISSION: "queue.veteran"
ADMINPERMISSION: "queue.admin"

# Queue server tab list configuration use %position% to show the current position of the player
# and use %wait% to show the estimated wait time of the player (not very accurate yet)
# this only shows when your in the queue waiting to join use a separate plugin for your main server
HEADER:
  - ""
  - " %server% "
  - ""
  - " %server% &bis full "
  - " Position in queue: &l%position% "
  - " &6Estimated time: &l%wait% "
  - ""

FOOTER:
  - ""
  - " &6You can now donate to receive priority queue status, please visit donate.SERVERNAME.org "
  - ""
  - " &7contact: someone@example.com "
  - " discussion: https://discord.example.com "
  - " website: https://www.example.com "
  - " These are the only official SERVERNAME websites and contacts "
  - ""

# Configs for priority queue tab list
HEADERPRIORITY:
  - ""
  - " %server%"
  - ""
  - " %server% &bis full "
  - " Position in queue: &l%position% "
  - " &6Estimated time: &l%wait% "
  - ""

FOOTERPRIORITY:
  - ""
  - " &6You have priority queue status please wait for an available slot on the server "
  - ""
  - " &7contact: someone@example.com "
  - " discussion: https://discord.example.com "
  - " website: https://www.example.com "
  - " These are the only official SERVERNAME websites and contacts "
  - ""

# Configs for veteran queue tab list
HEADERVETERAN:
  - ""
  - " %server% "
  - ""
  - " %server% &bis full "
  - " Position in queue: &l%position% "
  - " &6Estimated time: &l%wait% "
  - ""

FOOTERVETERAN:
  - ""
  - " &6You have veteran queue status please wait for an available slot on the server "
  - ""
  - " &7contact: someone@example.com "
  - " discussion: https://discord.example.com "
  - " website: https://www.example.com "
  - " These are the only official SERVERNAME websites and contacts "
  - ""
