name: XeraBungeeQueuePlaceholder
version: ${project.version}
main: me.alexprogrammerde.xerabungeequeueplaceholder.XeraBungeeQueuePlaceholder
api-version: 1.16
authors: [ AlexProgrammerDE ]
description: Puts queue data in papi
website: https://pistonmaster.net/
depend: [PlaceholderAPI]