name: PistonQueueBukkit
version: ${version}
api-version: 1.13
main: net.pistonmaster.pistonqueue.bukkit.PistonQueueBukkit
author: AlexProgrammerDE
description: Bukkit companion for PistonQueue
website: https://pistonmaster.net/
softdepend: [ "ProtocolLib" ]

permissions:
  queue.admin:
    description: Lets you bypass the plugin.
    default: op