package Leees.Bungee.Queue;

/**
 * Lang
 */
public class Lang {

    public static String SERVERISFULLMESSAGE, QUEUEPOSITION, JOININGMAINSERVER, QUEUEBYPASSPERMISSION,
            HEADER, FOOTER, POSITIONMESSAGEHOTBAR, QUEUESERVER,QUEUEPRIORITYPERMISSION, HEADERPRIORITY,
            FOOTERPRIORITY, REGEX, KICKMESSAGE, ADMINPERMISSION;
    public static int MAINSERVERSLOTS, ODDS, QUEUEMOVEDELAY;
}
