package net.pistonmaster.pistonqueue.bungee.utils;

import java.util.List;

/**
 * Config
 */
public final class Config {
    public static String SERVERISFULLMESSAGE, QUEUEPOSITION, JOININGMAINSERVER,
            QUEUEBYPASSPERMISSION, QUEUESERVER, QUEUEPRIORITYPERMISSION, REGEX,
            KICKMESSAGE, ADMINPERMISSION, MAINSERVER, AUTHSERVER, SERVERDOWNKICKMESSAGE,
            CUSTOMPROTOCOL, QUEUEVETERANPERMISSION, REGEXMESSAGE, PAUSEQUEUEIFMAINDOWNMESSAGE,
            SHADOWBANMESSAGE, IFMAINDOWNSENDTOQUEUEMESSAGE, RECOVERYMESSAGE;

    public static boolean POSITIONMESSAGEHOTBAR, ENABLEKICKMESSAGE, SERVERPINGINFOENABLE,
            ENABLEAUTHSERVER, ALWAYSQUEUE, CUSTOMPROTOCOLENABLE, REGISTERTAB, AUTHFIRST, POSITIONMESSAGECHAT,
            PAUSEQUEUEIFMAINDOWN, KICKWHENDOWN, FORCEMAINSERVER, ALLOWAUTHSKIP, IFMAINDOWNSENDTOQUEUE, RECOVERY;

    public static int MAINSERVERSLOTS, QUEUEMOVEDELAY, QUEUESERVERSLOTS, SERVERONLINECHECKDELAY, POSITIONMESSAGEDELAY;

    public static List<String> SERVERPINGINFO, HEADER, FOOTER, HEADERPRIORITY, FOOTERPRIORITY, HEADERVETERAN, FOOTERVETERAN;
}
