name: PistonQueuePlaceholder
version: ${project.version}
main: net.pistonmaster.pistonqueue.placeholder.PistonQueuePlaceholder
api-version: 1.13
authors: [ AlexProgrammerDE ]
description: Adds queue data to Placeholder API
website: https://pistonmaster.net/
depend: [ PlaceholderAPI ]